services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_visitas_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_visitas
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: api_visitas_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_visitas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local